### PR TITLE
feat/HTML Output to GH Pages

### PR DESCRIPTION
**Pull request by safrataxyz**
Added a python script that creates a HTML file according to Python Jinja template.

This script is called by workflow on GitHub and the output is then merged with output from JSON converter to be uploaded to GitHub Pages. Now there is HTML browser on https://dronetag.github.io/opendronelist/ and JSON _service_ on https://dronetag.github.io/opendronelist/models.json (etc...)

Also an updated README.md scopecreeped into this PR.

I haven't found a way to stop GitHub pages automatic build from repository - any idea on how to make it stop from running on push? It overwrites the new release created by the custom workflow.

### CODE REVIEW

**Comment by marianhlavac** [comment]
It's good, just for the output — is there a reason for why haven't we kept the table headings from the original template and used <td>'s instead of <th>'s or was that just an oversight?

**Comment by marianhlavac** [comment]
I'll check on the automatic builds, I've already disabled Github Pages in the repository settings and it seems that didn't do the trick.

Edit: Switched to _Actions_ in the settings, should behave properly now.
Screenshot 2022-07-28 at 13 04 02

**Comment by safrataxyz** [comment]
> It's good, just for the output — is there a reason for why haven't we kept the table headings from the original template and used 's instead of 's or was that just an oversight?

Just an oversight, fixed it

**Review by marianhlavac — APPROVED** [review]
Looks great, ready to ship!

**Pull request merged**
